#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Build a Fibonacci generator function"""


def fibonacci(maxint):
    """A fibonacci generator function

    Args:
        maxint(int): Serves as the upper bound for the loop

    Returns:
        A list of numbers generated by the loop

    Examples:
    >>> fibonacci(10)
    [0, 1, 1, 2, 3, 5, 8]

    """
    list1 = []
    int1, int2 = 0, 1
    while int2 < maxint:
        list1 = list1 + [int2]
        int1, int2 = int2, int1 + int2
    return list1
